version: "3.8"
services:

  # IDE in browser
  ide:
    build:
      context: .
      target: ide
    image: writing_quality_prediction_dev_image
    container_name: writing_quality_prediction_dev
    ports:
      - 8123:8123
      - 8080:8080
      - 40000:40000
    volumes:
      - .:/home/root/app
      - pre-commit:/root/.cache/pre-commit
      - poetry-cache:/root/.cache/pypoetry
      - $HOME/.gitconfig:/root/.gitconfig
      # 1.0 - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      # 2.0 (works)- /var/folders/d3/99dqnlcj3d53w4j9hx7sj43smd55py/T//ssh-3XEVfSc28dw1/agent.1285:/var/folders/d3/99dqnlcj3d53w4j9hx7sj43smd55py/T//ssh-3XEVfSc28dw1/agent.1285
      # 2.1 (fails)- $SSH_AUTH_SOCK:/var/folders/d3/99dqnlcj3d53w4j9hx7sj43smd55py/T//ssh-3XEVfSc28dw1/agent.1285
    #environment:
      #SSH_AUTH_SOCK: /tmp/authsock
      # 1.0 SSH_AUTH_SOCK: /ssh-agent
      # 2.0 (works)- SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    env_file:
      - .env_dev
    restart: unless-stopped
    command: "code-server --auth none --bind-addr 0.0.0.0:8123 /home/root/app"
    tty: true

  prod:
    build:
      context: .
      target: prod
    image: writing_quality_prediction_prod_image
    container_name: writing_quality_prediction_prod
    command: /bin/bash
    tty: true

volumes:
  vscode-extensions:
  pre-commit:
  poetry-cache: